# Generated by Django 5.1.6 on 2025-02-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
