# Generated by Django 5.1.6 on 2025-02-06 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0002_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visiting_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
    ]
